### ISSUE TITLE
Wrong service provider class in documentation

### ISSUE THREAD

**Issue by albertosabena** [phanan/cascading-config#1]
Hi, thanks for the great work!

Just a small note to notify you a problem in the documentation.
Seems that in the config/app.php is needed to add the line 

``` php
'PhanAn\CascadingConfig\CascadingConfigServiceProvider',
```

instead of 

``` php
'PhanAn\CascadingConfig\CascadingConfigProvider',
```

as you specified, after that it works like a charm!
Thank you!

**Comment by phanan** [comment]
Oops, sorry. I'm on a holiday, will fix once back. Or, if you could fork and fix it, I would be grateful for a PR ;)

**Comment by albertosabena** [comment]
Done! You've got a new pull request ;)

Bye and have a nice holiday!

**Comment by phanan** [comment]
Thanks a lot!
