### ISSUE TITLE
Folder Structure 

### ISSUE THREAD

**Issue by tapsboy** [phanan/cascading-config#3]
Thanks for creating this package so quickly after the 5.0 release. 

Wouldn't it be better to have the folder structure use nested configs instead of same level folders for each environment?

i.e. 
config/
config/local
config/prod/

instead of 

config
config.local
config.prod

Update: Mistakenly hit enter

**Comment by phanan** [comment]
It would certainly be better, if it was possible. Please see [this](https://github.com/phanan/laravel-5-cascading-config#notes) for the reason behind the chosen folder structure.
