### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by matiux** [phanan/cascading-config#9]
Lumen support?

**Comment by phanan** [comment]
I've never worked with Lumen, but this sounds like a great idea. Will look into it when I have time.

**Comment by phanan** [comment]
Actually no. From Lumen's [documentation](http://lumen.laravel.com/docs/installation#basic-configuration):

> Unlike the full-stack Laravel framework which has multiple configuration files, all of the configuration options for the Lumen framework are stored in a single `.env`configuration file.

So supporting Lumen is clearly out of this package's scope.

**Comment by phanan** [comment]
Sorry, I could't be more wrong. You can actually use a `config` folder. Will look at this.

**Comment by phanan** [comment]
I've added Lumen support as of v2.0.0. Sorry for taking this too long – I had to wait for Lumen to [support getting the configuration path](https://github.com/laravel/lumen-framework/commit/8800a2ed2bf87fff14140ca7e95d83970ab59198). Let me know if it works.
